# Project information
site_name: nnstt1 memo
site_author: nnstt1

# Repository
repo_name: nnstt1/docs
repo_url: https://github.com/nnstt1/docs

docs_dir: source
site_dir: docs

# Configuration
theme:
  name: material
  language: ja
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: teal
    accent: indigo

# Plugins
plugins:
  - search:
      lang:
        - en
        - ja
  - minify:
      minify_html: true

# Customization
extra:
  search:
    language: 'jp'

# Extensions
markdown_extensions:
  - admonition
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list

# Page tree
nav:
  - Tech:
    - index.md
    - MkDocs:
      - ./tech/mkdocs.md
    - Ansible:
      - ./tech/ansible/index.md
      - ./tech/ansible/tower.md
    - Kubernetes:
      - ./tech/kubernetes/operator/zalando-postgres-operator.md
    - Prometheus:
      - ./tech/prometheus/snmp-exporter.md
    - VMware:
      - ./tech/vmware/esxi.md
  - DIY:
    - ./diy/about.md