# Project information
site_name: nnstt1 memo
site_author: nnstt1

# Repository
repo_name: nnstt1/docs
repo_url: https://github.com/nnstt1/docs

# Configuration
theme:
  name: material
  language: ja
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: teal
    accent: indigo

# Plugins
plugins:
  - search:
      lang:
        - en
        - ja
  - minify:
      minify_html: true

# Customization
extra:
  search:
    language: 'jp'

# Extensions
markdown_extensions:
  - admonition
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - fontawesome_markdown

extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
  - stylesheets/extra.css

# Page tree
nav:
  - index.md
  - MkDocs:
    - ./mkdocs.md
  - Ansible:
    - ./ansible/index.md
    - ./ansible/tower.md
  - Kubernetes:
    - ./kubernetes/argocd.md
    - ./kubernetes/container-runtime.md
    - ./kubernetes/istio.md
    - ./kubernetes/maintenance.md
    - ./kubernetes/metallb.md
    - ./kubernetes/velero.md
    - Operator:
      - ./kubernetes/operator/rook.md
      - ./kubernetes/operator/zalando-postgres-operator.md
  - Prometheus:
    - ./prometheus/prometheus.md
    - ./prometheus/snmp-exporter.md
  - VMware:
    - ./vmware/esxi.md
