name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: build
        run: |
          mkdocs build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: nnstt1/nnstt1.github.io
          publish_branch: main
          publish_dir: ./site